Fix: CVE-2017-18925
OpenRC/opentmpfiles pull request #21
Opened 2022-04-29 10:13 UTC by KenjiBrown

Signed-off-by: Sandio Araico Sanchez <sandino@sandino.net>
Bug #540006
hardened mode for opentmpfiles
Ignore some recursive options
Refuse to remove root-owned dirs and files
Refuse to chmod/chdir/chown user-owned dirs and files
Check non-existence before creating a directory
Ensure directory has been newly created before chown/chmod/chgrp
exit on error

2022-04-30 01:32 UTC, vapier requested changes
please rebase onto the latest master branch

2022-05-25 00:36 UTC, thesamesam commented
Ping.

2022-05-25 02:17 UTC, KenjiBrown commented
I will do the rebase this weekend.

2022-05-31 08:00 UTC, KenjiBrown commented
Merge master
Rechecked correctness in variables: `"${path}" "${arg}" ${uid} ${gid} ${mode}`
Some `if [ $x -ne 0 ] ; then exit ; fi ` might be unnecessary.

2022-05-31 14:11 UTC, vapier commented
it doesn't seem like you've fully rebased onto the latest master branch yet

2022-05-31 17:45 UTC, KenjiBrown commented
I will better create a new clean branch and a new PR. Let me try...

2022-06-02 09:01 UTC, KenjiBrown commented
New clean PR is #22

2022-06-02 09:01 UTC, closed without merging